# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxOptional'
pod 'ESPullToRefresh'
pod 'ReSwift'
pod 'SnapKit'
pod 'ObjectMapper'
pod 'RxDataSources'
pod 'SwiftLint'

target 'ZhiHuDaily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiHuDaily

end
